# openapi2-appengine.yaml
swagger: '2.0'
info:
  title: daoAPI gateway
  description: Chatbot api gateway with an App Engine backend
  version: 1.0.0
schemes:
  - https
securityDefinitions:
  api_key:
    type: apiKey
    in: header
    name: X-API-KEY
produces:
  - application/json
x-google-management:
  metrics:
    # Define a metric for read requests.
    - name: "read-requests"
      displayName: "Read requests"
      valueType: INT64
      metricKind: DELTA
  quota:
    limits:
      # Define the limit or the read-requests metric.
      - name: "read-limit"
        metric: "read-requests"
        unit: "1/min/{project}" # 設定每 n 分鐘
        values:
          STANDARD: 3 # 上限可使用 n 次數
paths:
  /member:
    post:
      summary: Return a memberId.
      operationId: post_setmember
      x-google-backend:
        path_translation: APPEND_PATH_TO_ADDRESS
        address: {這裡要放 App Engine Domain Url}
        jwt_audience: {這裡要放用戶端編號}

      responses:
        '200':
          $ref: '#/responses/SuccessfulResponse'
        '401':
          $ref: '#/responses/UnauthorizedError'

  /footprint/{companyId}/{memberId}:
    get:
      summary: Return a list of footprintDatas.
      operationId: get_member
      parameters:
        - in: path
          name: companyId
          type: string
          required: true
        - in: path
          name: memberId
          type: string
          required: true
      x-google-backend:
        path_translation: APPEND_PATH_TO_ADDRESS
        address: {這裡要放 App Engine Domain Url}
        jwt_audience: {這裡要放用戶端編號}

      responses:
        '200':
          $ref: '#/responses/SuccessfulResponse'
        '401':
          $ref: '#/responses/UnauthorizedError'

  /footprint:
    post:
      summary: Return a string 'success'.
      operationId: post_footprint
      x-google-backend:
        path_translation: APPEND_PATH_TO_ADDRESS
        address: {這裡要放 App Engine Domain Url}
        jwt_audience: {這裡要放用戶端編號}

      responses:
        '200':
          $ref: '#/responses/SuccessfulResponse'
        '401':
          $ref: '#/responses/UnauthorizedError'

  /company/{companyId}:
    get:
      summary: Return a dictionary of companyData
      operationId: get_company
      parameters:
        - in: path
          name: companyId
          type: string
          required: true
      security:
        - api_key: []
      x-google-backend:
        path_translation: APPEND_PATH_TO_ADDRESS
        address: {這裡要放 App Engine Domain Url}
        jwt_audience: {這裡要放用戶端編號}

      responses:
        '200':
          $ref: '#/responses/SuccessfulResponse'
        '401':
          $ref: '#/responses/UnauthorizedError'

  /site/{companyId}/{siteId}:
    get:
      summary: Return a siteData wrap in list.
      operationId: get_site
      parameters:
        - in: path
          name: companyId
          type: string
          required: true
        - in: path
          name: siteId
          type: string
          required: true
      security:
        - api_key: []
      x-google-backend:
        path_translation: APPEND_PATH_TO_ADDRESS
        address: {這裡要放 App Engine Domain Url}
        jwt_audience: {這裡要放用戶端編號}

      responses:
        '200':
          $ref: '#/responses/SuccessfulResponse'
        '401':
          $ref: '#/responses/UnauthorizedError'

  /site/{companyId}:
    get:
      summary: Return a list of siteDatas.
      operationId: get_sites
      parameters:
        - in: path
          name: companyId
          type: string
          required: true
      security:
        - api_key: []
      x-google-backend:
        path_translation: APPEND_PATH_TO_ADDRESS
        address: {這裡要放 App Engine Domain Url}
        jwt_audience: {這裡要放用戶端編號}

      responses:
        '200':
          $ref: '#/responses/SuccessfulResponse'
        '401':
          $ref: '#/responses/UnauthorizedError'
  /site:
    post:
      summary: Return a string 'success'.
      operationId: post_site
      security:
        - api_key: []
      x-google-backend:
        path_translation: APPEND_PATH_TO_ADDRESS
        address: {這裡要放 App Engine Domain Url}
        jwt_audience: {這裡要放用戶端編號}

      responses:
        '200':
          $ref: '#/responses/SuccessfulResponse'
        '401':
          $ref: '#/responses/UnauthorizedError'

  /event:
    post:
      summary: Return an event with a list of infectedFootprints.
      operationId: post_eventData
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          "read-requests": 1 # 請求 n 次消耗的額度
      x-google-backend:
        path_translation: APPEND_PATH_TO_ADDRESS
        address: {這裡要放 App Engine Domain Url}
        jwt_audience: {這裡要放用戶端編號}

      responses:
        '200':
          $ref: '#/responses/SuccessfulResponse'
        '401':
          $ref: '#/responses/UnauthorizedError'

responses:
  UnauthorizedError:
    description: API key is missing or invalid
    headers:
      WWW_Authenticate:
        type: string
  SuccessfulResponse:
    description: A successful response
    schema:
      type: string
